// ================================
// DOMAIN ENTITIES
// ================================

export interface Deposit {
  id: string;
  amount: number;
  note: string;
  createdAt: string;
}

export interface Goal {
  id: string;
  name: string;
  target: number;
  deadline: string | null;
  createdAt: string;
  deposits: Deposit[];
}

// ================================
// INPUT TYPES
// ================================

/** Fields required to create a new goal — id, createdAt and deposits are generated by the store */
export type NewGoal = Pick<Goal, "name" | "target" | "deadline">;

/** Fields that can be edited on an existing goal */
export type GoalUpdates = Partial<Pick<Goal, "name" | "target" | "deadline">>;

/** Fields required to add a new deposit — id and createdAt are generated by the store */
export type NewDeposit = Pick<Deposit, "amount" | "note">;
